-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT) * P.PRICE AS SALES
from PRODUCT P JOIN OFFLINE_SALE S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY  P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC